# Generated by Django 4.2.18 on 2026-06-21 12:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarGeneration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('avatar_type', models.CharField(max_length=50)),
                ('provider', models.CharField(max_length=50)),
                ('provider_id', models.CharField(blank=True, max_length=255)),
                ('prompt', models.TextField(blank=True)),
                ('generated_url', models.CharField(blank=True, max_length=500)),
                ('cost_cents', models.IntegerField(blank=True, null=True)),
                ('generation_time_ms', models.IntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'avatar_generations',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('subdomain', models.CharField(max_length=100, unique=True)),
                ('custom_domain', models.CharField(blank=True, max_length=255, null=True)),
                ('niche', models.CharField(choices=[('indie_hacker', 'Indie Hacker'), ('freelancer', 'Freelancer'), ('creator', 'Creator'), ('coach', 'Coach/Consultant'), ('agency', 'Agency')], max_length=50)),
                ('niche_config', models.JSONField(blank=True, default=dict)),
                ('questionnaire', models.JSONField(blank=True, default=dict)),
                ('generated_html', models.TextField(blank=True)),
                ('generated_css', models.TextField(blank=True)),
                ('generated_metadata', models.JSONField(blank=True, default=dict)),
                ('avatar_type', models.CharField(blank=True, choices=[('photo', 'Photo'), ('3d', '3D'), ('2d_illustrated', '2D Illustrated'), ('ai_photo', 'AI Photo')], max_length=50)),
                ('avatar_url', models.CharField(blank=True, max_length=500)),
                ('avatar_generation_data', models.JSONField(blank=True, default=dict)),
                ('intro_card', models.JSONField(blank=True, default=dict)),
                ('intro_card_features', models.JSONField(blank=True, default=dict)),
                ('published_url', models.CharField(blank=True, max_length=255)),
                ('has_custom_domain', models.BooleanField(default=False)),
                ('custom_domain_status', models.CharField(blank=True, max_length=50)),
                ('netlify_site_id', models.CharField(blank=True, max_length=255)),
                ('generation_status', models.CharField(choices=[('text_pending', 'Text Pending'), ('text_done', 'Text Done'), ('avatar_pending', 'Avatar Pending'), ('avatar_done', 'Avatar Done'), ('publishing', 'Publishing'), ('live', 'Live'), ('failed', 'Failed')], default='text_pending', max_length=50)),
                ('deployment_status', models.CharField(choices=[('pending', 'Pending'), ('live', 'Live'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('last_deployed_at', models.DateTimeField(blank=True, null=True)),
                ('views', models.IntegerField(default=0)),
                ('visits', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('featured_at', models.DateTimeField(blank=True, null=True)),
                ('in_showcase', models.BooleanField(default=True)),
                ('showcase_rank', models.IntegerField(blank=True, null=True)),
                ('llm_provider', models.CharField(default='groq', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'portfolios',
            },
        ),
        migrations.CreateModel(
            name='PortfolioAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('views', models.IntegerField(default=0)),
                ('unique_visitors', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='portfolios.portfolio')),
            ],
            options={
                'db_table': 'portfolio_analytics',
            },
        ),
    ]
