# Generated by Django 4.2.18 on 2026-06-21 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='avatargeneration',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avatar_generations', to='portfolios.portfolio'),
        ),
        migrations.AlterUniqueTogether(
            name='portfolioanalytics',
            unique_together={('portfolio', 'date')},
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['user'], name='portfolios_user_id_f89dea_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['niche'], name='portfolios_niche_27a28d_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['in_showcase'], name='portfolios_in_show_846cac_idx'),
        ),
        migrations.AddIndex(
            model_name='avatargeneration',
            index=models.Index(fields=['portfolio'], name='avatar_gene_portfol_f0426d_idx'),
        ),
    ]
