# Generated by Django 4.2.18 on 2026-06-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_initial'),
        ('gallery', '0001_showcase_view'),
    ]

    operations = [
        # SQLite rebuilds the table on AddField; drop the dependent view first so
        # it doesn't block the rebuild. Gallery now queries Portfolio directly, so
        # the view is no longer needed.
        migrations.RunSQL(
            "DROP VIEW IF EXISTS showcase_index;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='custom_domain_token',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
